### ISSUE TITLE
Error Code 

### ISSUE THREAD

**Issue by brynnie1** [i-kulgu/ik-moneywash#1]
script:ik-moneywash] SCRIPT ERROR: @ik-moneywash/server.lua:18: attempt to perform arithmetic on a nil value (field 'worth')
 
 Not sure how to get around this or why its error on value

**Comment by i-kulgu** [comment]
Do you use markedbills that has value inside the info ?

**Comment by ghost** [comment]
how to add this? ^

**Comment by i-kulgu** [comment]
The default markedbills has his value inside the info.worth
You have probably changed that into an item with amount of that item but the name is still markedbills.
Thats the reason why it can't find the field worth and sends an error.

**Comment by ghost** [comment]
And Where can i find that?
